// Copyright Kameron Barnes
// SPDX-License-Identifier: MIT

#pragma once

#define ANSI_DEFINE(name, value) static const char *name = value

/* ANSI Control Sequences */
ANSI_DEFINE(ANSI_RESET, "\x1b[0m");
ANSI_DEFINE(ANSI_UNDERLINE, "\x1b[4m");
ANSI_DEFINE(ANSI_UNDERLINE_END, "\x1b[24m");
ANSI_DEFINE(ANSI_BOLD, "\x1b[1m");
ANSI_DEFINE(ANSI_BOLD_END, "\x1b[21m");
ANSI_DEFINE(ANSI_DIM, "\x1b[2m");
ANSI_DEFINE(ANSI_DIM_END, "\x1b[22m");
ANSI_DEFINE(ANSI_BLINK, "\x1b[5m");
ANSI_DEFINE(ANSI_BLINK_END, "\x1b[25m");
ANSI_DEFINE(ANSI_REVERSE, "\x1b[7m");
ANSI_DEFINE(ANSI_REVERSE_END, "\x1b[27m");
ANSI_DEFINE(ANSI_HIDE, "\x1b[8m");
ANSI_DEFINE(ANSI_HIDE_END, "\x1b[28m");

/* ANSI Text Colors */
ANSI_DEFINE(ANSI_BLACK_TEXT, "\x1b[30m");
ANSI_DEFINE(ANSI_RED_TEXT, "\x1b[31m");
ANSI_DEFINE(ANSI_GREEN_TEXT, "\x1b[32m");
ANSI_DEFINE(ANSI_YELLOW_TEXT, "\x1b[33m");
ANSI_DEFINE(ANSI_BLUE_TEXT, "\x1b[34m");
ANSI_DEFINE(ANSI_MAGENTA_TEXT, "\x1b[35m");
ANSI_DEFINE(ANSI_CYAN_TEXT, "\x1b[36m");
ANSI_DEFINE(ANSI_WHITE_TEXT, "\x1b[37m");
ANSI_DEFINE(ANSI_DEFAULT_TEXT, "\x1b[39m");

/* ANSI Background Colors */
ANSI_DEFINE(ANSI_BLACK_BACKGROUND, "\x1b[40m");
ANSI_DEFINE(ANSI_RED_BACKGROUND, "\x1b[41m");
ANSI_DEFINE(ANSI_GREEN_BACKGROUND, "\x1b[42m");
ANSI_DEFINE(ANSI_YELLOW_BACKGROUND, "\x1b[43m");
ANSI_DEFINE(ANSI_BLUE_BACKGROUND, "\x1b[44m");
ANSI_DEFINE(ANSI_MAGENTA_BACKGROUND, "\x1b[45m");
ANSI_DEFINE(ANSI_CYAN_BACKGROUND, "\x1b[46m");
ANSI_DEFINE(ANSI_WHITE_BACKGROUND, "\x1b[47m");
ANSI_DEFINE(ANSI_DEFAULT_BACKGROUND, "\x1b[49m");

/* Bright ANSI Text Colors */
ANSI_DEFINE(ANSI_BRIGHT_BLACK_TEXT, "\x1b[90m");
ANSI_DEFINE(ANSI_BRIGHT_RED_TEXT, "\x1b[91m");
ANSI_DEFINE(ANSI_BRIGHT_GREEN_TEXT, "\x1b[92m");
ANSI_DEFINE(ANSI_BRIGHT_YELLOW_TEXT, "\x1b[93m");
ANSI_DEFINE(ANSI_BRIGHT_BLUE_TEXT, "\x1b[94m");
ANSI_DEFINE(ANSI_BRIGHT_MAGENTA_TEXT, "\x1b[95m");
ANSI_DEFINE(ANSI_BRIGHT_CYAN_TEXT, "\x1b[96m");
ANSI_DEFINE(ANSI_BRIGHT_WHITE_TEXT, "\x1b[97m");

/* Bright ANSI Background Colors */
ANSI_DEFINE(ANSI_BRIGHT_BLACK_BACKGROUND, "\x1b[100m");
ANSI_DEFINE(ANSI_BRIGHT_RED_BACKGROUND, "\x1b[101m");
ANSI_DEFINE(ANSI_BRIGHT_GREEN_BACKGROUND, "\x1b[102m");
ANSI_DEFINE(ANSI_BRIGHT_YELLOW_BACKGROUND, "\x1b[103m");
ANSI_DEFINE(ANSI_BRIGHT_BLUE_BACKGROUND, "\x1b[104m");
ANSI_DEFINE(ANSI_BRIGHT_MAGENTA_BACKGROUND, "\x1b[105m");
ANSI_DEFINE(ANSI_BRIGHT_CYAN_BACKGROUND, "\x1b[106m");
ANSI_DEFINE(ANSI_BRIGHT_WHITE_BACKGROUND, "\x1b[107m");

#undef ANSI_DEFINE
